// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCodigoProgramacionBack.Utilities;

namespace SistemaCodigoProgramacionBack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240127153801_codigo")]
    partial class codigo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaCodigoProgramacionBack.Models.Codigo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcionCorta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("imagenPortada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("linkCodigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tituloCodigo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("codigos");
                });
#pragma warning restore 612, 618
        }
    }
}
